

%%
format compact;
directory = 'C:\Users\ME-IT\Desktop\AllisonRaptureTestData\17Feb2012 Alex\';

% directory = 'E:\Gait Variability Study\Control Group\Alex 24Feb12\Rapture Data\';

tdmsFilenamesForTrials = { ...
%   {'standing', 1}, ...
%   {'8deg_forward_notouch', 1}, ...
%   {'8deg_forward_notouch', 2}, ...
%   {'8deg_forward_touching', 1}, ...
%   {'8deg_backward_touching', 1}, ...
%   {'4deg_foward_notouch', 1}, ...
%   {'4deg_backward_notouch', 1}, ...
%   {'4deg_forward_touching', 1}, ...
%   {'4deg_backward_touching', 1}, ...
%   {'10deg_forward_notouch', 1}, ...
%   {'10deg_backward_notouch', 1}, ...
%   {'10deg_forward_touching', 1}, ...
%   {'10deg_backward_touching', 1}, ...
%   {'0deg_forward_notouch', 1}, ...
%   {'0deg_forward_touching', 1}, ...
%   };
  {'testimuincdec', 2}, ...
  {'testimuincdec', 3}, ...
  {'testimuincdec', 4}, ...
  {'testimuincdec', 5}, ...
  ...{'testimuincdec', 6}, ...
  {'testimuincdec', 7}, ...
  {'testimuincdec', 8}, ...
  {'testimuincdec', 9}, ...
  {'testimuincdec', 10}, ...
  {'testimuincdec', 11}, ...
  {'testimuincdec', 12}, ...
  {'testimuincdec', 13}, ...
  {'testimuincdec', 14}, ...
  {'testimuincdec', 15}, ...
  {'testimuincdec', 16}, ...
  };

trialNumbersToProcess = 1:16;
trialNumbersToProcess(6) = [];
trialNumbersToProcess(1) = [];

% anglesForTrial = [0, 8, 8, 8, 8, 4, 4, 4, 4, 10, 10, 10, 10, 0, 0];
% speedsForTrial = [0, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, 1];

anglesForTrial = [4, 4, 4, 4, 10, 10, 10, 10, 0, 0, 8, 8, 8, 8];
speedsForTrial = [1, -1, 1, -1, 1, -1, 1, -1, 1, 1, 1, -1, 1, -1];

tdmsDirectory = [directory '1) Treadmill Desktop Data\tdms\'];
c3dDirectory = [directory '2) Recap2\'];
customLogDirectory = [directory '1) Treadmill Desktop Data\customlog\'];
outputC3DDirectory = [directory '3) CombinedC3d\'];
tdmsFilename = [tdmsDirectory 'testimuincdec.tdms'];

for trialNumberIndex = 1:14 % %6 %
  
  trialNumber = trialNumbersToProcess(trialNumberIndex);
  
  tdmsFilenameAndNumber = tdmsFilenamesForTrials{trialNumberIndex};
  %   tdmsFilename = [tdmsDirectory tdmsFilenameAndNumber{1} '.tdms'];
  %     tdmsTabNumber = trialNumber; % use this if you are loading in one tdms
  %file, with each tab corresponding to one trial
  tdmsTabNumber = tdmsFilenameAndNumber{2}; %trialNumber; %
  customPhasespaceLogName = [customLogDirectory sprintf('phasespaceCustomLog%d.txt', trialNumber)];
  c3dFilenameToLoad = [c3dDirectory sprintf('Trial %02d.c3d', trialNumber)];
  outputFilename = [outputC3DDirectory sprintf('trial%02d', trialNumber) '-' tdmsFilenameAndNumber{1} '.c3d'];
  
  angle = anglesForTrial(trialNumberIndex);
  speed = speedsForTrial(trialNumberIndex);
  
  [phasespaceAndAnalogStructure] = savePhasespaceAndAnalogDataInC3D( ...
    customPhasespaceLogName, tdmsFilename, tdmsTabNumber, ...
    c3dFilenameToLoad, outputFilename, 'c3dUnitsAreInMeters', 1, ...
    'forceReprocess', 0, ...
    'shouldFillGapsInMarkerData', 0, ...
    'parameterDataToWrite', {{'ANGLE', angle}, {'SPEED', speed}} ...
    );
end

%% for 1 specific trial, use this

% customPhasespaceLogName = [directory 'phasespaceCustomLog14.txt'];
% tdmsFilename = [directory '0deg_forward_notouch.tdms'];
% tdmsTabNumber = 1;
% c3dFilenameToLoad =[directory 'Trial 14.c3d'];
% outputFilename =[directory '0deg_forward_notouchCombined.c3d'];
% 
% 
% [phasespaceAndAnalogStructure] = savePhasespaceAndAnalogDataInC3D( ...
%   customPhasespaceLogName, tdmsFilename, tdmsTabNumber, ...
%   c3dFilenameToLoad, outputFilename,'shouldFillGapsInMarkerData', 0, 'c3dUnitsAreInMeters', 1);



% , 'c3dUnitsAreInMeters', 1, ...
%   'shouldFillGapsInMarkerData', 0);




